-- MySQL Script generated by MySQL Workbench
-- Út 23. únor 2016, 22:46:41 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prometheus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prometheus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prometheus` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `prometheus` ;

-- -----------------------------------------------------
-- Table `prometheus`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prometheus`.`player` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(60) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_active` TIMESTAMP NULL,
  `last_login` TIMESTAMP NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `prometheus`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prometheus`.`log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NULL,
  `message` TEXT NOT NULL,
  `inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  INDEX `fk_log_1_idx` (`player_id` ASC),
  CONSTRAINT `fk_log_1`
    FOREIGN KEY (`player_id`)
    REFERENCES `prometheus`.`player` (`player_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `prometheus`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prometheus`.`chat` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`chat_id`),
  INDEX `fk_chat_1_idx` (`sender_id` ASC),
  CONSTRAINT `fk_chat_1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `prometheus`.`player` (`player_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `prometheus`.`receiver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prometheus`.`receiver` (
  `receiver_id` INT NOT NULL AUTO_INCREMENT,
  `chat_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`receiver_id`),
  INDEX `fk_receiver_1_idx` (`chat_id` ASC),
  INDEX `fk_receiver_2_idx` (`player_id` ASC),
  CONSTRAINT `fk_receiver_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `prometheus`.`chat` (`chat_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receiver_2`
    FOREIGN KEY (`player_id`)
    REFERENCES `prometheus`.`player` (`player_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
